# Generated by Django 4.0.5 on 2022-09-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='user_id',
        ),
        migrations.AddField(
            model_name='login',
            name='token',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
