# Generated by Django 4.0.5 on 2022-09-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_remove_login_user_id_login_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.EmailField(max_length=254)),
                ('password', models.EmailField(max_length=254)),
                ('token', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
