# Generated by Django 4.0.5 on 2022-09-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_token_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='token',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='token',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
