# Generated by Django 4.1.1 on 2022-09-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0004_employee_alter_token_password_alter_token_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
