# Generated by Django 4.1.1 on 2022-09-12 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0005_user_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="password",
        ),
    ]
