# Generated by Django 4.1.1 on 2022-09-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0007_user_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="password",
        ),
        migrations.AddField(
            model_name="user",
            name="pas",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
